//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D DirtSampler;
//   float3 LuminanceConstants;
//   sampler2D SpecSampler;
//   sampler2D TextureSampler;
//   sampler2D TextureSampler2;
//   float3 dirtColor;
//   float dirtLevel;
//   float4 gDirectionalLight;
//   float4 globalScalars;
//   float3 matDiffuseColor;
//   float4 matDiffuseColor2;
//   float reflectivePowerED;
//   float3 specMapIntMask;
//   float3 specular2Color;
//   float specular2ColorIntensityED;
//   float specular2FactorED;
//   float specularColorFactorED;
//   float specularFactorED;
//   float4 stencil;
//
//
// Registers:
//
//   Name                      Reg   Size
//   ------------------------- ----- ----
//   gDirectionalLight         c17      1
//   globalScalars             c39      1
//   stencil                   c52      1
//   matDiffuseColor           c66      1
//   matDiffuseColor2          c72      1
//   dirtLevel                 c73      1
//   dirtColor                 c74      1
//   specularFactorED          c75      1
//   specularColorFactorED     c76      1
//   specMapIntMask            c77      1
//   specular2FactorED         c78      1
//   specular2ColorIntensityED c79      1
//   specular2Color            c80      1
//   reflectivePowerED         c81      1
//   LuminanceConstants        c82      1
//   TextureSampler            s0       1
//   TextureSampler2           s1       1
//   DirtSampler               s2       1
//   SpecSampler               s4       1
//

    ps_3_0
    def c127, 0.9999999, 1, 0, 0	// LogDepth constants
    def c0, 9.99999975e-006, 1.9, 0.150000006, 0
    def c1, 1, 0, 6.80000019, 9.99999975e-005
    def c2, -13.2877121, 0.5, 0.1953125, 0
    def c3, 5.2, 1.7, 0.35, 0 // x - fresnel power, y - reflection side power, z - reflection front power
    dcl_texcoord v0
    dcl_texcoord1 v1.xyz
    dcl_texcoord3 v2.xyz
    dcl_color v3
    dcl_texcoord9 v9
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s4
    texld r0, v0, s0
    texld r1, v0.zwzw, s1
    add r2.xyz, c0.x, v1
    dp3 r2.w, r2, r2
    rsq r2.w, r2.w
    mul r3.xyz, r2, r2.w
    add r4.xyz, c0.x, v2
    nrm r8.xyz, r4
    dp3 r9.x, -r8, r3
    mov_sat r9.y, -r9.x
    add r9.y, r9_abs.y, c1.x
    pow r9.y, r9.y, c3.x
    rcp r9.y, r9.y
    mad r9.y, r9.y, c3.y, c3.z
    texld r4, v0, s4
    mul r3.w, r4.w, c81.x
    mul r3.w, r3.w, c0.y
    mul r3.w, r3.w, r9.y
    dp3 r4.x, r4, c77
    mul r4.x, r4.x, c81.x
    mul r4.x, r4.x, c0.z
    mul r4.x, r4.x, r9.y
    mul r4.yzw, r0.xxyz, c66.xxyz
    mul r1, r1, c72
    lrp r0.xyz, r1.w, r1, r4.yzww
    mul r0, r0, v3
    dp3 r1.x, v3, c82
    mul oC2.z, r1.x, c39.z
    mov r1.yzw, c0
    if_lt -c73.x, r1.w
      texld r5, v0, s2
      mul r1.x, r5.x, c73.x
      mov r6.x, c1.x
      mad r6.x, r5.x, -c73.x, r6.x
      lrp r6.yzw, r1.x, c74.xxyz, r0.xxyz
      mad r7, r0.xxyz, c1.yxxx, c1.xyyy
      cmp r5, -r5.x, r7, r6
      mov r0.xyz, r5.yzww
    else
      mov r5.x, c1.x
    endif
    mul r1.x, r4.x, r5.x
    mov r5.xyz, c1
    mul r1.w, r5.z, c78.x
    mul r1.y, r1.y, c75.x
    rcp r1.y, r1.y
    mul r1.y, r3.w, r1.y
    mul r1.z, r1.z, c76.x
    rcp r1.z, r1.z
    mul r1.z, r4.x, r1.z
    mul r1.y, r1.w, r1.y
    mul r1.w, c79.x, c79.x
    mul r1.z, r1.z, r1.w
    mul r4.xyz, r1.z, c80
    add r1.z, r9.x, r9.x
    mad r3.xyz, r3, -r1.z, -r8
    dp3 r1.z, -c17, r3
    add r1.w, r1.z, c1.w
    log r1.w, r1.w
    cmp r1.z, r1.z, r1.w, c2.x
    mul r1.y, r1.y, r1.z
    exp r1.y, r1.y
    mad r1.yzw, r4.xxyz, r1.y, r0.xxyz
    cmp oC0.xyz, -c79.x, r0, r1.yzww
    mul r0.x, r1.x, c72.w
    mul r0.y, r3.w, c72.w
    mad r1.xyz, r2, r2.w, c1.x
    mul r0.w, r0.w, c39.x
    mov oC0.w, r0.w
    mul oC1.xyz, r1, c2.y
    mov oC1.w, r0.w
    mul oC2.x, r0.x, c2.y
    mul r0.x, r0.y, c2.z
    rsq r0.x, r0.x
    rcp oC2.y, r0.x
    mov oC2.w, c1.x
    mul oC3, r5.xyyy, c52.x
	// ----------------------------------------------------------------- Linear2Log -----------------------------------------------------------------
	if_ne v9.y, c127.y
		rcp r20.z, c128.x
		mul r20.x, v9.w, r20.z
		mul r20.y, c128.y, r20.z
		log r20.x, r20.x
		log r20.y, r20.y
		rcp r20.y, r20.y
	else
		mov r20.x, v9.z
		rcp r20.y, v9.w
	endif
	mul oDepth, r20.x, r20.y
	// ----------------------------------------------------------------------------------------------------------------------------------------------

// approximately 74 instruction slots used (4 texture, 70 arithmetic)
