//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D ConvertSampler;
//   float4 gShadowParam18192021;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   gShadowParam18192021 c53      1
//   ConvertSampler       s0       1
//

    ps_3_0
    def c0, 1, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld r0, v0, s0
    mul oC0, r0, c0

// approximately 18 instruction slots used (4 texture, 14 arithmetic)
