//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D DepthMapTexSampler;
//   sampler2D DiffuseTexSampler;
//   float HybridAdd;
//   float4 gInvScreenSize;
//   float gSoftness;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   gSoftness          c66      1
//   HybridAdd          c72      1
//   NearFarPlane       c128     1
//   gInvScreenSize     c129     1
//   DiffuseTexSampler  s0       1
//   DepthMapTexSampler s12      1
//

    ps_3_0
    def c0, 0.5, 0.212500006, 0.715399981, 0.0720999986
    def c1, -1, 1, 0, 0
    dcl_color v0
    dcl_texcoord v1
    dcl_texcoord1 v2.zw
    dcl_texcoord2 v3.y
    dcl_texcoord3 v4
    dcl_texcoord4 v5.xy
    dcl vPos.xy
    dcl_2d s0
    dcl_2d s12
    mad r0.xy, vPos, c129, c129.zwzw
    texld r0, r0, s12

    // linearize depth buffer from near to far plane
    mov r20.xy, c128.zz
    add r20.y, r20.y, c128.w
    mad r20.z, r0.x, -r20.x, r20.y
    rcp r0.x, r20.z

    add r0.x, r0.x, -v3.y
    mul r0.x, r0.x, r0.x
    mul_sat r0.x, r0.x, c66.x
    mul r0.w, r0.x, v0.w
    texld r1, v1, s0
    texld r2, v1.zwzw, s0
    lrp r3, c0.x, r2, r1
    mov r0.xyz, v0
    mul r0, r0, r3
    mul r1.xyz, r0, v5.y
    dp3 r1.x, r1, c0.yzww
    mad r1.yzw, r0.xxyz, v5.y, -r1.x
    mov_sat r0.w, r0.w
    mad r1.yzw, v2.z, r1, r1.x
    add r2.x, c1.x, v2.w
    pow r3.x, r1_abs.x, r2.x
    mul r2.xyz, r1.yzww, r3.x
    mad r1.xyz, r1.yzww, -r3.x, v4
    mad r0.xyz, v4.w, r1, r2
    mul r1.xyz, r0.w, r0
    add r2.x, c1.y, -v5.x
    mul r1.w, r0.w, r2.x
    abs r2.x, c72.x
    cmp r0, -r2.x, r0, r1
    max oC0, r0, c1.z

// approximately 29 instruction slots used (3 texture, 26 arithmetic)
